### ISSUE TITLE
Make "Setting up Environment Variables" section in readme a little more clear for clientID

### ISSUE THREAD

**Issue by rizcheldayao** [IBM/rotisserie#101]
I just forked and cloned the repo down. Everything was pretty straightforward except for the "Setting up Environment Variables" section. I didn't know where to get the clientID from. It might be good if we add in the docs that you need to create a Twitch app and get the clientID from there.

I can make this change if everyone is okay with it.

**Comment by pwplusnick** [comment]
Go for it!
